-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 12:18:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RentACar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RentACar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RentACar` DEFAULT CHARACTER SET utf8 ;
USE `RentACar` ;

-- -----------------------------------------------------
-- Table `RentACar`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Cliente` (
  `ClienteId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClienteNombre` VARCHAR(20) NOT NULL,
  `ClienteApellido` VARCHAR(20) NULL,
  `ClienteCorreo` VARCHAR(45) NULL,
  `ClienteEdad` INT NULL,
  `ClienteGenero` VARCHAR(1) NULL,
  PRIMARY KEY (`ClienteId`),
 CONSTRAINT check_clienteGenero CHECK (ClienteGenero in ('Femenino', 'Masculino','Otro')),
  UNIQUE INDEX `ClienteId_UNIQUE` (`ClienteId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Oficina` (
  `OficinaId` INT NOT NULL AUTO_INCREMENT,
  `OficinaNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`OficinaId`),
  UNIQUE INDEX `OficinaId_UNIQUE` (`OficinaId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`DocumentoIdentidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`DocumentoIdentidad` (
  `DocumentoIdentidadId` INT NOT NULL AUTO_INCREMENT,
  `DocumentoIdentidad` VARCHAR(45) NULL,
  PRIMARY KEY (`DocumentoIdentidadId`),
  UNIQUE INDEX `DocumentoIdentidadId_UNIQUE` (`DocumentoIdentidadId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`DocumentoIdentidadTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`DocumentoIdentidadTipo` (
  `DocumentoIdentidadTipoId` INT NOT NULL AUTO_INCREMENT,
  `DocumentoIdentidadTipo` VARCHAR(20) NULL,
  `DocumentoIdentidadId` INT NOT NULL,
  PRIMARY KEY (`DocumentoIdentidadTipoId`),
  INDEX `fk_DocumentoIdentidadTipo_DocumentoIdentidad1_idx` (`DocumentoIdentidadId` ASC) VISIBLE,
  UNIQUE INDEX `DocumentoIdentidadTipoId_UNIQUE` (`DocumentoIdentidadTipoId` ASC) VISIBLE,
  CONSTRAINT `fk_DocumentoIdentidadTipo_DocumentoIdentidad1`
    FOREIGN KEY (`DocumentoIdentidadId`)
    REFERENCES `RentACar
   `.`DocumentoIdentidad` (`DocumentoIdentidadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Factura` (
  `FacturaId` INT NOT NULL AUTO_INCREMENT,
  `FacturaFecha` DATE NULL,
  `FacturaPrecio` DOUBLE NULL,
  `FacturaITBIS` DOUBLE NULL,
  `FacturaTotal` DOUBLE NULL,
  PRIMARY KEY (`FacturaId`),
  UNIQUE INDEX `FacturaId_UNIQUE` (`FacturaId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Alquiler` (
  `AlquilerId` INT NOT NULL AUTO_INCREMENT,
  `AlquilerCodigo` VARCHAR(10) NULL,
  `AlquilerFechaDe` DATE NULL,
  `AlquilerFechaHasta` DATE NULL,
  `Factura_FacturaId` INT NOT NULL,
  `ClienteId` INT UNSIGNED NOT NULL,
  `OficinaId` INT NOT NULL,
  PRIMARY KEY (`AlquilerId`),
  INDEX `fk_Alquiler_Factura1_idx` (`Factura_FacturaId` ASC) VISIBLE,
  INDEX `fk_Alquiler_Cliente1_idx` (`ClienteId` ASC) VISIBLE,
  INDEX `fk_Alquiler_Oficina1_idx` (`OficinaId` ASC) VISIBLE,
  UNIQUE INDEX `AlquilerId_UNIQUE` (`AlquilerId` ASC) VISIBLE,
  CONSTRAINT `fk_Alquiler_Factura1`
    FOREIGN KEY (`Factura_FacturaId`)
    REFERENCES `RentACar
   `.`Factura` (`FacturaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Cliente1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `RentACar
   `.`Cliente` (`ClienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_Oficina1`
    FOREIGN KEY (`OficinaId`)
    REFERENCES `RentACar
   `.`Oficina` (`OficinaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Carro` (
  `CarroId` INT NOT NULL AUTO_INCREMENT,
  `CarroMatricula` VARCHAR(10) NULL,
  `CarroChasis` VARCHAR(10) NULL,
  `CarroPlaca` VARCHAR(10) NULL,
  `CarroKilometraje` INT(10) NULL,
  `CarroEstado` VARCHAR(10) NULL,
  PRIMARY KEY (`CarroId`),
ONSTRAINT check_carroEstado CHECK (CarroEstado in ('Alquilado', 'Disponible')),
  UNIQUE INDEX `CarroId_UNIQUE` (`CarroId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Reserva` (
  `ReservaId` INT NOT NULL AUTO_INCREMENT,
  `ReservaCodigo` VARCHAR(10) NULL,
  `ReservaAlquilerFechaDe` DATE NULL,
  `ReservaAlquilarFechaHasta` DATE NULL,
  `FacturaId` INT NOT NULL,
  `ClienteId` INT UNSIGNED NOT NULL,
  `CarroId` INT NOT NULL,
  `OficinaId` INT NOT NULL,
  PRIMARY KEY (`ReservaId`),
  INDEX `fk_Reserva_Factura1_idx` (`FacturaId` ASC) VISIBLE,
  INDEX `fk_Reserva_Cliente1_idx` (`ClienteId` ASC) VISIBLE,
  INDEX `fk_Reserva_Carro1_idx` (`CarroId` ASC) VISIBLE,
  INDEX `fk_Reserva_Oficina1_idx` (`OficinaId` ASC) VISIBLE,
  UNIQUE INDEX `ReservaId_UNIQUE` (`ReservaId` ASC) VISIBLE,
  UNIQUE INDEX `ReservaCodigo_UNIQUE` (`ReservaCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Factura1`
    FOREIGN KEY (`FacturaId`)
    REFERENCES `RentACar
   `.`Factura` (`FacturaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `RentACar
   `.`Cliente` (`ClienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Carro1`
    FOREIGN KEY (`CarroId`)
    REFERENCES `RentACar
   `.`Carro` (`CarroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Oficina1`
    FOREIGN KEY (`OficinaId`)
    REFERENCES `RentACar
   `.`Oficina` (`OficinaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Motor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Motor` (
  `MotorId` INT NOT NULL AUTO_INCREMENT,
  `MotorNombre` VARCHAR(45) NULL,
  `CarroId` INT NOT NULL,
  PRIMARY KEY (`MotorId`, `CarroId`),
  INDEX `fk_Motor_Carro1_idx` (`CarroId` ASC) VISIBLE,
  UNIQUE INDEX `MotorId_UNIQUE` (`MotorId` ASC) VISIBLE,
  CONSTRAINT `fk_Motor_Carro1`
    FOREIGN KEY (`CarroId`)
    REFERENCES `RentACar
   `.`Carro` (`CarroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Color` (
  `ColorId` INT NOT NULL AUTO_INCREMENT,
  `ColorNombre` VARCHAR(45) NULL,
  `CarroId` INT NOT NULL,
  PRIMARY KEY (`ColorId`, `CarroId`),
  INDEX `fk_Color_Carro1_idx` (`CarroId` ASC) VISIBLE,
  UNIQUE INDEX `ColorId_UNIQUE` (`ColorId` ASC) VISIBLE,
  CONSTRAINT `fk_Color_Carro1`
    FOREIGN KEY (`CarroId`)
    REFERENCES `RentACar
   `.`Carro` (`CarroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Marca` (
  `MarcaId` INT NOT NULL AUTO_INCREMENT,
  `MarcaNombre` VARCHAR(45) NULL,
  `CarroId` INT NOT NULL,
  PRIMARY KEY (`MarcaId`, `CarroId`),
  INDEX `fk_Marca_Carro1_idx` (`CarroId` ASC) VISIBLE,
  UNIQUE INDEX `MarcaId_UNIQUE` (`MarcaId` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Carro1`
    FOREIGN KEY (`CarroId`)
    REFERENCES `RentACar
   `.`Carro` (`CarroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Modelo` (
  `ModeloId` INT NOT NULL AUTO_INCREMENT,
  `ModeloNombre` VARCHAR(45) NULL,
  `MarcaId` INT NOT NULL,
  PRIMARY KEY (`ModeloId`, `MarcaId`),
  INDEX `fk_Modelo_Marca1_idx` (`MarcaId` ASC) VISIBLE,
  UNIQUE INDEX `ModeloId_UNIQUE` (`ModeloId` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`MarcaId`)
    REFERENCES `RentACar
   `.`Marca` (`MarcaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`ClienteOficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`ClienteOficina` (
  `ClienteOficinaId` INT NOT NULL AUTO_INCREMENT,
  `OficinaId` INT NOT NULL,
  `ClienteId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ClienteOficinaId`, `OficinaId`, `ClienteId`),
  INDEX `fk_ClienteOficina_Oficina1_idx` (`OficinaId` ASC) VISIBLE,
  INDEX `fk_ClienteOficina_Cliente1_idx` (`ClienteId` ASC) VISIBLE,
  UNIQUE INDEX `ClienteOficinaId_UNIQUE` (`ClienteOficinaId` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteOficina_Oficina1`
    FOREIGN KEY (`OficinaId`)
    REFERENCES `RentACar
   `.`Oficina` (`OficinaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteOficina_Cliente1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `RentACar
   `.`Cliente` (`ClienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Telefonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Telefonia` (
  `TelefoniaId` INT NOT NULL AUTO_INCREMENT,
  `TelefoniaNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`TelefoniaId`),
  UNIQUE INDEX `TelefoniaId_UNIQUE` (`TelefoniaId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Telefono` (
  `TelefonoId` INT NOT NULL AUTO_INCREMENT,
  `TelefonoNumero` VARCHAR(45) NULL,
  `TelefoniaId` INT NOT NULL,
  PRIMARY KEY (`TelefonoId`),
  UNIQUE INDEX `TelefonoId_UNIQUE` (`TelefonoId` ASC) VISIBLE,
  INDEX `fk_Telefono_Telefonia1_idx` (`TelefoniaId` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Telefonia1`
    FOREIGN KEY (`TelefoniaId`)
    REFERENCES `RentACar
   `.`Telefonia` (`TelefoniaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Provincia` (
  `ProvinciaId` INT NOT NULL AUTO_INCREMENT,
  `ProvinciaNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`ProvinciaId`),
  UNIQUE INDEX `ProvinciaId_UNIQUE` (`ProvinciaId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Municipio` (
  `MunicipioId` INT NOT NULL AUTO_INCREMENT,
  `MunicipioNombre` VARCHAR(45) NULL,
  `ProvinciaId` INT NOT NULL,
  PRIMARY KEY (`MunicipioId`),
  UNIQUE INDEX `MunicipioId_UNIQUE` (`MunicipioId` ASC) VISIBLE,
  INDEX `fk_Municipio_Provincia1_idx` (`ProvinciaId` ASC) VISIBLE,
  CONSTRAINT `fk_Municipio_Provincia1`
    FOREIGN KEY (`ProvinciaId`)
    REFERENCES `RentACar
   `.`Provincia` (`ProvinciaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Sector` (
  `SectorId` INT NOT NULL AUTO_INCREMENT,
  `SectorNombre` VARCHAR(45) NULL,
  `MunicipioId` INT NOT NULL,
  PRIMARY KEY (`SectorId`),
  UNIQUE INDEX `SectorId_UNIQUE` (`SectorId` ASC) VISIBLE,
  INDEX `fk_Sector_Municipio1_idx` (`MunicipioId` ASC) VISIBLE,
  CONSTRAINT `fk_Sector_Municipio1`
    FOREIGN KEY (`MunicipioId`)
    REFERENCES `RentACar
   `.`Municipio` (`MunicipioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`Direccion` (
  `DireccionId` INT NOT NULL AUTO_INCREMENT,
  `DireccionCasa` VARCHAR(45) NULL,
  `DireccionCalle` VARCHAR(45) NULL,
  `SectorId` INT NOT NULL,
  PRIMARY KEY (`DireccionId`),
  UNIQUE INDEX `DireccionId_UNIQUE` (`DireccionId` ASC) VISIBLE,
  INDEX `fk_Direccion_Sector1_idx` (`SectorId` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Sector1`
    FOREIGN KEY (`SectorId`)
    REFERENCES `RentACar
   `.`Sector` (`SectorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`ClienteTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`ClienteTelefono` (
  `ClienteTelefonoId` INT NOT NULL AUTO_INCREMENT,
  `ClienteId` INT UNSIGNED NOT NULL,
  `TelefonoId` INT NOT NULL,
  PRIMARY KEY (`ClienteTelefonoId`),
  INDEX `fk_ClienteTelefono_Cliente1_idx` (`ClienteId` ASC) VISIBLE,
  INDEX `fk_ClienteTelefono_Telefono1_idx` (`TelefonoId` ASC) VISIBLE,
  UNIQUE INDEX `ClienteTelefonoId_UNIQUE` (`ClienteTelefonoId` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteTelefono_Cliente1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `RentACar
   `.`Cliente` (`ClienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteTelefono_Telefono1`
    FOREIGN KEY (`TelefonoId`)
    REFERENCES `RentACar
   `.`Telefono` (`TelefonoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`OficinaTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`OficinaTelefono` (
  `OficinaTelefonoId` INT NOT NULL AUTO_INCREMENT,
  `OficinaId` INT NOT NULL,
  `TelefonoId` INT NOT NULL,
  PRIMARY KEY (`OficinaTelefonoId`),
  INDEX `fk_OficinaTelefono_Oficina1_idx` (`OficinaId` ASC) VISIBLE,
  INDEX `fk_OficinaTelefono_Telefono1_idx` (`TelefonoId` ASC) VISIBLE,
  UNIQUE INDEX `OficinaTelefonoId_UNIQUE` (`OficinaTelefonoId` ASC) VISIBLE,
  CONSTRAINT `fk_OficinaTelefono_Oficina1`
    FOREIGN KEY (`OficinaId`)
    REFERENCES `RentACar
   `.`Oficina` (`OficinaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OficinaTelefono_Telefono1`
    FOREIGN KEY (`TelefonoId`)
    REFERENCES `RentACar
   `.`Telefono` (`TelefonoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`ClienteDireccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`ClienteDireccion` (
  `ClienteDireccionId` INT NOT NULL AUTO_INCREMENT,
  `ClienteId` INT UNSIGNED NOT NULL,
  `DireccionId` INT NOT NULL,
  PRIMARY KEY (`ClienteDireccionId`),
  INDEX `fk_ClienteDireccion_Cliente1_idx` (`ClienteId` ASC) VISIBLE,
  INDEX `fk_ClienteDireccion_Direccion1_idx` (`DireccionId` ASC) VISIBLE,
  UNIQUE INDEX `ClienteDireccionId_UNIQUE` (`ClienteDireccionId` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteDireccion_Cliente1`
    FOREIGN KEY (`ClienteId`)
    REFERENCES `RentACar
   `.`Cliente` (`ClienteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteDireccion_Direccion1`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `RentACar
   `.`Direccion` (`DireccionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`OficinaDireccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`OficinaDireccion` (
  `OficinaDireccionId` INT NOT NULL AUTO_INCREMENT,
  `OficinaId` INT NOT NULL,
  `DireccionId` INT NOT NULL,
  PRIMARY KEY (`OficinaDireccionId`),
  INDEX `fk_OficinaDireccion_Oficina1_idx` (`OficinaId` ASC) VISIBLE,
  INDEX `fk_OficinaDireccion_Direccion1_idx` (`DireccionId` ASC) VISIBLE,
  UNIQUE INDEX `OficinaDireccionId_UNIQUE` (`OficinaDireccionId` ASC) VISIBLE,
  CONSTRAINT `fk_OficinaDireccion_Oficina1`
    FOREIGN KEY (`OficinaId`)
    REFERENCES `RentACar
   `.`Oficina` (`OficinaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OficinaDireccion_Direccion1`
    FOREIGN KEY (`DireccionId`)
    REFERENCES `RentACar
   `.`Direccion` (`DireccionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RentACar`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RentACar`.`DetalleFactura` (
  `DetalleFacturaId` INT NOT NULL AUTO_INCREMENT,
  `CarroId` INT NOT NULL,
  `FacturaId` INT NOT NULL,
  PRIMARY KEY (`DetalleFacturaId`),
  UNIQUE INDEX `DetalleFacturaId_UNIQUE` (`DetalleFacturaId` ASC) VISIBLE,
  INDEX `fk_DetalleFactura_Carro1_idx` (`CarroId` ASC) VISIBLE,
  INDEX `fk_DetalleFactura_Factura1_idx` (`FacturaId` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleFactura_Carro1`
    FOREIGN KEY (`CarroId`)
    REFERENCES `RentACar
   `.`Carro` (`CarroId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFactura_Factura1`
    FOREIGN KEY (`FacturaId`)
    REFERENCES `RentACar
   `.`Factura` (`FacturaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
